swagger: '2.0'
info:
  version: '1.0.0'
  title: Domain API
  description: This is a read-only API that returns the base domain of LivePerson that should be used in the APIs outlined in this document.
  termsOfService: http://helloreverb.com/terms/
  contact:
    name: Swagger API team
    email: foo@example.com
    url: http://swagger.io
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
host: petstore.swagger.io
basePath: api.liveperson.net/api/account
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /{account}/service/{serviceName}/baseURI.json?version=1.0:
    get:
      description: Returns the base domain of LivePerson
      operationId: Request
      produces:
        - application/json
        - application/xml
        - text/xml
        - text/html
      parameters:
        - name: account
          in: path
          description: LivePerson account ID
          required: true
          type: string
        - name: serviceName
          in: path
          description: The service to fetch
          required: true
          type: string
      responses:
        '200':
          description: Response
          schema:
            $ref: '#/definitions/service'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  service:
    type: object
    required:
      - service
      - account
      - baseURI
    properties:
      service:
        type: string
      account:
        type: string
      baseURI:
        type: string
  errorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
